version: "3.8"

services:
    db:
        image: mongo:latest
        env_file:
            - .env
        environment:
            - MONGO_INITDB_DATABASE=circles
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        ports:
            - "${MONGO_PORT}:${MONGO_PORT}"
        volumes:
            - db:/data/db
        restart: always
        networks:
            - webnet

    minio:
        image: minio/minio
        env_file:
            - .env
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USERNAME}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server /data --console-address :9001
        ports:
            - "${MINIO_PORT}:${MINIO_PORT}"
            - "9001:9001"
        volumes:
            - storage:/data
        networks:
            - webnet

    qdrant:
        image: qdrant/qdrant
        environment:
            QDRANT__SERVICE__GRPC_PORT: 6334
            QDRANT__SERVICE__HTTP_PORT: 6333
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - qdrant_data:/qdrant/storage
        restart: always
        networks:
            - webnet

    postgres:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_USER: synapse_user
            POSTGRES_PASSWORD: synapse_password
            POSTGRES_DB: synapse
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - webnet

    synapse:
        image: matrixdotorg/synapse:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - SYNAPSE_SERVER_NAME=${CIRCLES_DOMAIN}
            - SYNAPSE_REPORT_STATS=yes
            - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
            - SYNAPSE_NO_TLS=1
            - SYNAPSE_POSTGRES=1
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=synapse_user
            - POSTGRES_PASSWORD=synapse_password
            - POSTGRES_DB=synapse
        volumes:
            - synapse_data:/data
        networks:
            - webnet

    nginx:
        image: nginx:latest
        env_file:
            - .env
        volumes:
            - ./nginx.conf.local:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80"
        networks:
            - webnet
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - minio

volumes:
    db:
    storage:
    qdrant_data:
    postgres_data:
    synapse_data:

networks:
    webnet:
