version: "3.8"

services:
    circles:
        env_file:
            - .env
            - .env.local

    db:
        env_file:
            - .env
            - .env.local

    minio:
        env_file:
            - .env
            - .env.local

    nginx:
        env_file:
            - .env
            - .env.local
