version: "3.8"
services:
    circles:
        image: alpine # dummy service to prevent errors
        command: ["sh", "-c", "echo 'Dummy Circles service' && tail -f /dev/null"]
        networks:
            - webnet
    watchtower:
        profiles: ["do-not-start"]

    db:
        env_file:
            - .env
            - .env.local

    minio:
        env_file:
            - .env
            - .env.local

    nginx:
        env_file:
            - .env
            - .env.local
        environment:
            - CIRCLES_HOST=host.docker.internal
            - CIRCLES_PORT=${CIRCLES_PORT}
        extra_hosts:
            - "host.docker.internal:host-gateway"
