version: "3.8"

services:
    db:
        image: mongo:latest
        env_file:
            - .env
        environment:
            - MONGO_INITDB_DATABASE=circles
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        ports:
            - "${MONGO_PORT}:${MONGO_PORT}"
        volumes:
            - db:/data/db
        restart: always
        networks:
            - webnet

    minio:
        image: minio/minio
        env_file:
            - .env
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USERNAME}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server /data --console-address :9001
        ports:
            - "${MINIO_PORT}:${MINIO_PORT}"
            - "9001:9001"
        volumes:
            - storage:/data
        networks:
            - webnet

    nginx:
        image: nginx:latest
        env_file:
            - .env
        volumes:
            - ./nginx.conf.local:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80"
        networks:
            - webnet
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - minio

volumes:
    db:
    storage:

networks:
    webnet:
