version: "3"
services:
    app:
        build: .
        ports:
            - "3000:3000"
        environment:
            - MONGODB_URI=mongodb://mongo:27017/circles_registry
            - JWT_SECRET=your_jwt_secret_here
        depends_on:
            - db
    db:
        image: mongo:latest
        environment:
            - MONGO_INITDB_DATABASE=circles_registry
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        ports:
            - "27017:27017"
        volumes:
            - db:/data/db

volumes:
    db:
