version: "3.8"

services:
    app:
        image: sslorg/circles-registry:latest
        environment:
            - MONGO_HOST=${MONGO_HOST}
            - MONGO_PORT=${MONGO_PORT}
            - MONGO_INITDB_ROOT_USERNAME=${REGISTRY_MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${REGISTRY_MONGO_ROOT_PASSWORD}
        depends_on:
            - db
        networks:
            - registry_network

    db:
        image: mongo:latest
        environment:
            - MONGO_INITDB_DATABASE=circlesRegistry
            - MONGO_INITDB_ROOT_USERNAME=${REGISTRY_MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${REGISTRY_MONGO_ROOT_PASSWORD}
        volumes:
            - registry_db:/data/db
        networks:
            - registry_network
        ports:
            - "27018:27017"

    nginx:
        image: nginx:latest
        ports:
            - "3001:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        networks:
            - registry_network

    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        environment:
            WATCHTOWER_POLL_INTERVAL: 300 # Check for updates every 5 minutes

networks:
    registry_network:
        name: circles_registry_network

volumes:
    registry_db:
        name: circles_registry_db
